MVC-ActionLink-DiplomadoUASD/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_ActionLink_DiplomadoUASD.Controllers
{
    public class ClientesController : Controller
    {
        // GET: Clientes
       
        public ActionResult Listado()
        {
            return View();
        }

        public ActionResult Crear()
        {
            return View();
        }
    }
}

MVC-ActionLink-DiplomadoUASD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_ActionLink_DiplomadoUASD.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC-ActionLink-DiplomadoUASD/Controllers/ProveedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_ActionLink_DiplomadoUASD.Controllers
{
    public class ProveedoresController : Controller
    {
        // GET: Proveedores
        
        public ActionResult Listado()
        {
            return View();
        }
        public ActionResult Crear()
        {
            return View();
        }
    }
}

MVC-ActionLink-DiplomadoUASD/Views/Clientes/Crear.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crear</title>
</head>
<body>
    <div>
        <h1>Crear Cliente</h1>
        <ul>
            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
            <li>@Html.ActionLink("Listado Cliente", "Listado", "Clientes")</li>
            <li>@Html.ActionLink("Listado Proveedores", "Listado", "Proveedores")</li>
            <li>@Html.ActionLink("Crear Proveedores", "Crear", "Proveedores")</li>
        </ul>

    </div>
</body>
</html>

MVC-ActionLink-DiplomadoUASD/Views/Clientes/Listado.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Listado</title>
</head>
<body>
    <div>
        <h1>Listado de Clientes</h1>
        <ul>
            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
            <li>@Html.ActionLink("Crear Cliente", "Crear", "Clientes")</li>
            <li>@Html.ActionLink("Listado Proveedores", "Listado", "Proveedores")</li>
            <li>@Html.ActionLink("Crear Proveedor", "Crear", "Proveedores")</li>
        </ul>
      
    </div>
</body>
</html>

MVC-ActionLink-DiplomadoUASD/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
   <div>
       <h1>Pagina Principal</h1>
       <ul>
       <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
       <li>@Html.ActionLink("Listado Clientes", "Listado", "Clientes")</li>
       <li>@Html.ActionLink("Crear Clientes", "Crear", "Clientes")</li>
       <li>@Html.ActionLink("Listado Proveedores", "Listado", "Proveedores")</li>
       <li>@Html.ActionLink("Crear proveedores", "Crear", "Proveedores")</li>
       </ul>
   </div>
   
</body>
</html>

MVC-ActionLink-DiplomadoUASD/Views/Proveedores/Crear.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crear</title>
</head>
<body>
    <div>
        <h1>Crear Proveedor</h1>
        <ul>
            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
            <li>@Html.ActionLink("Listado de Clientes", "Listado", "Clientes")</li>
            <li>@Html.ActionLink("Crear Cliente", "Crear", "Clientes")</li>
            <li>@Html.ActionLink("Listado Proveedores", "Listado", "Proveedores")</li>

        </ul>
        
    </div>
</body>
</html>

MVC-ActionLink-DiplomadoUASD/Views/Proveedores/Listado.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Listado</title>
</head>
<body>
    <div>
        <h1>Listado de Proveedores</h1>
        <ul>
            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
            <li>@Html.ActionLink("Listado Clientes", "Listado", "Clientes")</li>
            <li>@Html.ActionLink("Crear Cliente", "Crear", "Clientes")</li>
            <li>@Html.ActionLink("Crear Proveedor", "Crear", "Proveedores")</li>
        </ul>
        
    </div>
</body>
</html>